---
version: '2'
services:
  unifi:
    image: derektamsen/unifi
    build: ./
    mem_limit: 768m
    cpu_shares: 512
    restart: on-failure:5
    volumes:
      - unifidata:/usr/lib/unifi/data
      - unifilog:/usr/lib/unifi/logs
      - unifidl:/usr/lib/unifi/dl
    links:
      - mongo
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8880:8880"
      - "8843:8843"
      - "3478:3478/udp"
      - "10001:10001/udp"
  mongo:
    image: mongo:3
    mem_limit: 512m
    cpu_shares: 512
    restart: on-failure:5
    ulimits:
      nproc: 64000
      nofile:
        soft: 64000
        hard: 64000
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db
volumes:
  unifidata:
    driver: local
  unifilog:
    driver: local
  unifidl:
    driver: local
  mongodata:
    driver: local
