---
version: '3.2'
services:
  unifi:
    image: derektamsen/unifi
    build: ./
    restart: on-failure:5
    volumes:
      - unifidata-nfs:/usr/lib/unifi/data
      - unifilog-nfs:/usr/lib/unifi/logs
      - unifidl-nfs:/usr/lib/unifi/dl
    links:
      - mongo
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8880:8880"
      - "8843:8843"
      - "3478:3478/udp"
      - "10001:10001/udp"
  mongo:
    image: mongo:3
    restart: on-failure:5
    ulimits:
      nproc: 64000
      nofile:
        soft: 64000
        hard: 64000
    expose:
      - "27017"
    volumes:
      - mongodata-nfs:/data/db
volumes:
  unifidata-nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},nolock,soft,rw"
      device: ":${NFS_VOLUME_DATA}"
  unifilog-nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},nolock,soft,rw"
      device: ":${NFS_VOLUME_LOG}"
  unifidl-nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},nolock,soft,rw"
      device: ":${NFS_VOLUME_DL}"
  mongodata-nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},nolock,soft,rw"
      device: ":${NFS_VOLUME_MONGO}"
